[project]
name = "auto_insurance_agent"
version = "0.0.1"
dependencies = [
    "cloudpickle",
    "db_dtypes",
    "dotenv",
    "google-adk(>=1.14.1, <1.15.0)",
    "google-cloud-aiplatform[agent_engines]",
    "google-cloud-bigquery",
    "pandas",
    "pydantic"
]
