[project]
name = "pdf_summary_agent"
version = "0.0.1"
dependencies = [
    "google-cloud-aiplatform[agent_engines]",
    "google-adk(>=1.18.0, <1.19.0)",
    "google-cloud-storage"
    "pandas",
    "db_dtypes",
    "cloudpickle",
    "dotenv"
]
